version: '3.8'

services:
  web:
    build: .
    command: python core/server.py
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: flask_app_db
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: flask_password
    ports:
      - "5432:5432"
